// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtO21YlHuM4H_uicxcy-D04S8K5x-G-84',
    appId: '1:672320788929:web:8187343a0bdc695db9f740',
    messagingSenderId: '672320788929',
    projectId: 'pms2024-b3b8c',
    authDomain: 'pms2024-b3b8c.firebaseapp.com',
    storageBucket: 'pms2024-b3b8c.appspot.com',
    measurementId: 'G-C627GX3H4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkciZFXe3kAO2kSmkYbF3BnkMoe0P6f2k',
    appId: '1:672320788929:android:afed0ca6c7c64732b9f740',
    messagingSenderId: '672320788929',
    projectId: 'pms2024-b3b8c',
    storageBucket: 'pms2024-b3b8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHRkJgDebAGD-izH4vgSD0EtUDIPkzcKA',
    appId: '1:672320788929:ios:bf1522b2e0f50d8eb9f740',
    messagingSenderId: '672320788929',
    projectId: 'pms2024-b3b8c',
    storageBucket: 'pms2024-b3b8c.appspot.com',
    iosBundleId: 'com.example.pms2024',
  );
}
